### ISSUE TITLE
Multiple workflow support

### ISSUE THREAD

**Issue by UberMouse** [abskmj/hukum#10]
Hey, great job, love the concept of this. However, I, unfortunately, can't make proper use of it as it stands because we use a monorepo at work. This means that a given commit can trigger multiple workflows (probably around 7 at most) and hukum seems to just show the first workflow triggered?

Would love a mode that showed less detail (maybe just the current step for each workflow?) but showed all the workflows that were running for the commit.

**Comment by abskmj** [comment]
Thanks!

Yes, I also found out that this limitation when I started using it for one of the other projects. I'm planning to update it soon.

A 'crisp' mode would be a good idea for multiple workflows.
