### ISSUE TITLE
Could terminal output be shown too?

### ISSUE THREAD

**Issue by antoniogamiz** [abskmj/hukum#12]
I mean, right now is quite useful, but is something fails I still have to go to the action page to see what has gone wrong.

**Comment by abskmj** [comment]
I have been looking for a way to do from the start but, unfortunately Github doesn't have an API to stream the logs. The closest possible is to download the log file through [this](https://docs.github.com/en/rest/reference/actions#download-workflow-run-logs) API.

**Comment by antoniogamiz** [comment]
Mmm, could you download them if there's an error and show them? I mean, at the end of the workflow.

**Comment by abskmj** [comment]
I believe the error won't be present in the last few lines of the file as GitHub cleanup happens in the last step. The output would be complex for multiple workflows. 

Maybe it can just download and keep the log file in a local folder when there is an error.

**Comment by antoniogamiz** [comment]
That would work, yeah :). Or maybe a flag to open the workflow status page in the default browser. Or both :D.
Sorry if I am asking too much.

**Comment by stephenmathieson** [comment]
An option to open the workflow in a browser if it fails would be nice!

**Comment by abskmj** [comment]
I have added [links to the workflow names](https://github.com/abskmj/hukum/blob/master/CHANGELOG.md#140) in the latest release. In case the terminal doesn't support HTTP links, the links will be printed in full next to the workflow names. These links are clickable and should open on the default browser. Let me know if this helps.

**Comment by antoniogamiz** [comment]
Uoh, you're great! Thanks a lot, really :).

**Comment by antoniogamiz** [comment]
I have noticed than if I run `hukum` after making a commit, my github actions workflow starts. My workflow has 3 different jobs and I can see the output of the first one. The problem is that when that job finishes, it does not show the other two. 

Do you know why? Maybe this problem should be in a different issue.

**Comment by abskmj** [comment]
Could you please close this and open an new issue ? Will continue the discussion there. Thanks.
