### ISSUE TITLE
Workflows with multiple jobs are not shown sequentially

### ISSUE THREAD

**Issue by antoniogamiz** [abskmj/hukum#18]
I have noticed than if I run `hukum` after making a commit, my [github actions workflow](https://github.com/Raku/Documentable/blob/develop/.github/workflows/integration-run.yml) starts. My workflow has 3 different jobs and I can see the output of the first one. The problem is that when the first job finishes, it does not show the other two.

~~~
{
  branch: 'develop',
  hash: '4ebd76a27f08e81fed8de39bc14b93a59ea0661e',
  author: 'antoniogamiz10@gmail.com',
  repo: 'Raku/Documentable'
}
   Fix some problems with :pragma<keep-unused-variables>, refs #117 (​https://github.com/Raku/Documentable/actions/runs/183317042​)
     ✔ build-base-container 109s
       ✔ Set up job 2s
       ✔ Build elgohr/Publish-Docker-Github-Action@master 29s
       ✔ Run actions/checkout@master 4s
       ✔ Publish to Registry 73s
       ✔ Post Run actions/checkout@master 0s
       ✔ Complete job 1s
~~~
And tha'ts all it shows.

**Comment by abskmj** [comment]
Thanks for sharing the logs. They are helpful. I think I got where the problem is.

**Comment by abskmj** [comment]
Would you mind testing the changes on your local before I release a new version? 

You can remove the current version on your local by executing `npm remove -g hukum` and install this version by executing `npm install -g abskmj/hukum#release/1.5.0`

**Comment by antoniogamiz** [comment]
Everything is working nicely:

~~~
{
  branch: 'develop',
  hash: '5d30a8c393b5d9cf8258fd6ad8e9c9094f1797a5',
  author: 'antoniogamiz10@gmail.com',
  repo: 'Raku/Documentable'
}

   Set debug flag to find the error
     Run integration tests with the official doc suite (​https://github.com/Raku/Documentable/actions/runs/185518509​)
     ✔ build-base-container 101s
       ✔ Complete job 1s
     ✔ build-documentable-container 303s
       ✔ Complete job 0s
     ✔ build-documentation 76s
       ✔ Complete job 0s
     ▶ build-official-doc 80s
       ▶ Run git clone -b master --single-branch https://github.com/Raku/doc.git 51s

~~~

Thanks a lot!!!! :-)

**Comment by antoniogamiz** [comment]
Oh, if you press enter while `hukum` is running it stops running. Is that normal?

**Comment by abskmj** [comment]
Thanks for testing it out! I'll put this for next release.

Yes, you can press `enter` key to exit out of `hukum`.

**Comment by antoniogamiz** [comment]
Cool :).
