### ISSUE TITLE
Cannot read property 'head_commit' of undefined

### ISSUE THREAD

**Issue by ivan-andrei-blazic** [abskmj/hukum#2]
I set up a .hukumrc file and added a token to my repository but when I run hukum I receive, "_TypeError: Cannot read property 'head_commit' of undefined
    at Object.module.exports.start (/usr/local/lib/node_modules/hukum/lib/hukum.js:24:32)"
_

**Comment by abskmj** [comment]
Thanks for reporting this bug, I will add a fix and release a new version in couple of days.
