### ISSUE TITLE
Works only in Node 12

### ISSUE THREAD

**Issue by rstar2** [abskmj/hukum#20]
Because of the Strings.matchAll() usage which is available in Node 12 and later for lower Node versions the module cannot be used.

`const getRepo = async () => {
  const remotes = await git.getRemotes(true)
  const gh = remotes.find((remote) => remote.refs.push.includes('github.com'))

  const matches = gh.refs.push.matchAll(/github.com[/:](.*?)\/(.*?)\.git$/g)

  for (const match of matches) {
    return `${match[1]}/${match[2]}`
  }
}`

Would be better this simple patch be "fixed" and not restrict to only Node 12 version. Node 10 is still havily used

**Comment by abskmj** [comment]
Oh, I accidentally broke it. I will also add compatibility checks to the GitHub workflow as well. Thanks for letting me know.

**Comment by a20185** [comment]
we've use the following for implementation, and works fine on Node 8

```javascript
/** ignore previous logic */
const [project, repository] = pushRepository.split('/').slice(-2)
return `${project}/${repository.endsWith('.git') ? repository.slice(0, -4) : repository}`
```

**Comment by abskmj** [comment]
@a20185 Your implementation might not support ssh remotes like `git@github.com:abskmj/hukum.git`. Regex based implementation works for most possible [Git URL formats](https://stackoverflow.com/questions/31801271/what-are-the-supported-git-url-formats). Thanks for the info though. I will push a fix for this in some time.

**Comment by ljharb** [comment]
Heads up that you can use https://npmjs.com/string.prototype.matchall to get the functionality in every engine.

**Comment by abskmj** [comment]
@ljharb Although I have refactored the code already, this is good to know.
