### ISSUE TITLE
Repo undefined if origin URL don't end with `.git`

### ISSUE THREAD

**Issue by kbakk** [abskmj/hukum#21]
Hello,

I'm using hukum 1.5.1 (latest, I can see). 

When I run `hukum`, it outputs:

```
❯ hukum --version
{
  branch: 'master',
  hash: '9152b77035f1778e82912cc6849a6c2cee91be41',
  author: 'email@example.com',
  repo: undefined
}
Error: Request failed with status code 404
...
    baseURL: 'https://api.github.com/repos/undefined/actions',
...
```

I don't think my repo is set in any strange ways. But it's using http instead of git.

Seeing that hukum is using `git remote` (equivalent?) here's the output of that:

```
❯ git remote -v
origin  https://github.com/my-organization/my-repo (fetch)
origin  https://github.com/my-organization/my-repo (push)
```

It's working on a different repo (seemingly set up the same way as the first). Any idea what could be wrong?

**Comment by abskmj** [comment]
It looks for `.git` at the end of the remote URL. In your case, it should have been
```
❯ git remote -v
origin  https://github.com/my-organization/my-repo.git (fetch)
origin  https://github.com/my-organization/my-repo.git (push)
```
Could you please check if your other repo has it?

**Comment by kbakk** [comment]
Indeed, it's missing it, and the other repo had it.

Running `git remote set-url origin https://github.com/my-organization/my-repo.git` and now hukum works.

**Comment by abskmj** [comment]
Thanks for confirming, I will keep the issue open for a fix as https URLs without `.git` are also valid.
