### ISSUE TITLE
Possible to set global/default .hukumrc?

### ISSUE THREAD

**Issue by wallentx** [abskmj/hukum#3]
This is a very helpful tool, but since I'd be using mostly for private org repos with a self-hosted runner, I need to have a .hukumrc file in every repo. Is there a way to pass the token via envar, or have a user/global default .hukumrc?

**Comment by abskmj** [comment]
I was also thinking in a similar direction when I started to use Hukum on multiple projects. I think an environment variable like `HUKUM_GITHUB_TOKEN` makes sense here. I will add it and release a new version in a couple of days.
